language: node_js
node_js:
  - "4.1"
  - "0.11"
  - "0.10"
  - "0.8"
matrix:
  allow_failures:
    - node_js: "0.11"
script: "nyc --reporter=html --reporter=text ./node_modules/mocha/bin/_mocha test/*.js -- -R spec && rm -rf ./coverage && rm -rf ./.nyc_output"
after_success: npm run coverage
